---
version: 2
project_name: lintnet

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*

builds:
  - binary: lintnet
    main: cmd/lintnet/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/lintnet/lintnet/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/lintnet/lintnet/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/lintnet/lintnet/compare/{{.PreviousTag}}...{{.Tag}}

homebrew_casks:
  - repository:
      owner: lintnet
      name: homebrew-lintnet
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/lintnet/lintnet
    description: |
      Secure, Powerful, Reusable Configuration file linter powered by Jsonnet
    license: MIT
    skip_upload: true
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lintnet"]
          end

scoops:
  - description: |
      Secure, Powerful, Reusable Configuration file linter powered by Jsonnet
    license: MIT
    skip_upload: true
    repository:
      owner: lintnet
      name: scoop-bucket

sboms:
  - id: default
    disable: false
