#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

help=$(lintnet help-all)

echo "---
sidebar_position: 500
---

# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$help" > docs/guides/usage.md
