---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@bb77a49e569726f192ee8b704883c1da618c4516 # v4.0.1
    with:
      aqua_version: v2.55.1
      golangci-lint-timeout: 120s
    permissions:
      pull-requests: write
      contents: read

  integration-test:
    uses: ./.github/workflows/wc-integration-test.yaml
    permissions: {}

  test_doc:
    uses: ./.github/workflows/workflow_call_deploy_doc.yaml
    permissions:
      contents: write
      issues: write
